DIRECTORY:
  dataset: /content/drive/MyDrive/KoreanBeef/data/01_splitdataset
  sample: /content/drive/MyDrive/KoreanBeef/data/sample_submission.csv
  phase: test

TRAIN:
  train_serial: 'CONVNEXT_20220620_120012'

PREDICT:
  seed: 42
  gpu: 0