DIRECTORY:
  dataset: /content/drive/MyDrive/KoreanBeef/data/01_splitdataset
  sample: /content/drive/MyDrive/KoreanBeef/data/sample_submission.csv
  phase: test

TRAIN: # results/ 폴더 안에 새로 생긴 모델 결과 경로
  train_serial: '/content/drive/MyDrive/KoreanBeef/results/train/20220609_072048_CONVNET'

PREDICT:
  seed: 42
  gpu: 0