DIRECTORY:
  dataset: /content/drive/MyDrive/KoreanBeef/data/01_splitdataset/

TRAINER :
  model: convnxt # 모델 변경에 따라 값을 변경
  optimizer: adamw
  learning_rate: 5.0e-4
  loss: crossentropy
  metric:
    - accuracy
    - f1macro
  n_epochs: 50
  early_stopping_target: val_accuracy
  early_stopping_patience: 10
  early_stopping_mode: max
  amp: False
  gpu: 0
  seed: 42
  
MODEL: # 사용 모델 추가
  Linear:
    n_inputs:  784
    n_outputs: 5
  effnet:
    n_outputs: 5
  resnet:
    n_outputs: 5
  convnxt:
    n_outputs: 5

DATALOADER:
  batch_size: 16
  num_workers: 1
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  wandb: False
  logging_interval: 100
  plot:
    - loss
    - accuracy
    - f1macro
    - elapsed_time

